EXTRACTION_PROMPT = """
You are an expert legal data extraction AI. 
Review the following extracted OCR text (which may contain noise or typos) and extract the key structured data.

Return ONLY a valid JSON object with the following keys:
- "document_title" (string)
- "dates" (list of strings)
- "parties" (list of strings)
- "case_numbers" (list of strings)
- "document_type" (string)

If a field cannot be found, return an empty list or null for that key. Do not invent data.

Text to extract from:
{raw_text}
"""

DRAFTING_PROMPT = """
You are an AI Legal Drafter. Your task is to generate a {draft_type} based STRICTLY on the provided evidence chunks.

CRITICAL INSTRUCTIONS:
1. Grounding: Every claim you make MUST be supported by the provided evidence. 
2. No Assumptions: Do not generate confident-sounding text built on unsupported assumptions.
3. Citations: You must cite the evidence chunk ID for every major fact. Example: "The lease was signed in 2021 [ID: chunk_05]".
4. Learned Rules: Follow these rules gathered from past operator edits to format your output:
{learned_rules}

EVIDENCE CHUNKS:
{evidence_context}

Now, generate the {draft_type}:
"""

FEEDBACK_LEARNING_PROMPT = """
You are an AI system analyst. Your job is to improve future drafting by learning from operator edits.

Compare the ORIGINAL DRAFT generated by the AI and the EDITED DRAFT corrected by a human operator.
Identify the core structural, stylistic, or formatting change the operator made (e.g., changing date formats, removing passive voice, restructuring headings).

Extract this as a single, clear, reusable rule (1-2 sentences) that an AI can apply to future drafts. 
Do NOT reference specific case details, names, or numbers. Only extract the underlying pattern.

ORIGINAL DRAFT:
{original_draft}

EDITED DRAFT:
{edited_draft}

REUSABLE RULE:
"""